### ISSUE TITLE
Invalid value com.github.hpgrahsl.kafka.connect.transforms.kryptonite.CipherField$Value, for configuration transforms.cipher.type: Class com.github.hpgrahsl.kafka.connect.transforms.kryptonite.CipherField$Value, could not be found.

### ISSUE THREAD

**Issue by sfc-gh-adlee** [hpgrahsl/kryptonite-for-kafka#12]
As per the suggestion, I tried to configure but it showed that it was not able to find the value. I ensured I have the jar file inside my path (kryptonite-0.4.1.jar and connect-transform-kryptonite-0.4.1.jar)  I see that it is loaded. Any reason why com.github.hpgrahsl.kafka.connect.transforms.kryptonite.CipherField$Value is not working?

**Comment by hpgrahsl** [comment]
I'm afraid that if you get this error your kafka connect configuration must be wrong somehow. It clearly shows that the kryptonite SMT hasn't been loaded successfully during bootstrap of your connect worker process. Please verify in the logs that the jar can be located and properly loaded while kafka connect starts.

**Comment by hpgrahsl** [comment]
@sfc-gh-adlee could you verify your kafka connect configuration? I hope you were able to sort it out. As this problem doesn't seem to be related to the SMT of this library I'm going to close the issue for now. Feel free to re-open it if necessary.
