### ISSUE TITLE
Cannot decrypt int64 (long) fields

### ISSUE THREAD

**Issue by wdutkiewicz** [hpgrahsl/kryptonite-for-kafka#13]
Hi, @hpgrahsl

I encountered an error when trying to decrypt fields of type long (INT64). I believe there is a bug in [TypeSchemaMapper.java](https://github.com/hpgrahsl/kryptonite-for-kafka/blob/d291eeee830a093542c1dc7e32e3f6913da349cf/connect-transform-kryptonite/src/main/java/com/github/hpgrahsl/kafka/connect/transforms/kryptonite/TypeSchemaMapper.java#L49C30-L49C30)

```
Map<Type, Supplier<SchemaBuilder>> DEFAULT_MAPPINGS_DECRYPT =
      Map.of(
          Type.BOOLEAN, SchemaBuilder::bool,
          Type.INT8, SchemaBuilder::int8,
          Type.INT16, SchemaBuilder::int16,
          Type.INT32, SchemaBuilder::int32,
          Type.INT64, SchemaBuilder::int16,
          Type.FLOAT32, SchemaBuilder::float32,
          Type.FLOAT64, SchemaBuilder::float64,
          Type.STRING, SchemaBuilder::string,
          Type.BYTES, SchemaBuilder::bytes
      );
```

`INT64` is mapped to `int16` - shouldn't it be `int64`?

**Comment by hpgrahsl** [comment]
Yes, good catch. That's a bug indeed. THX for reporting this.

**Comment by hpgrahsl** [comment]
Will be addressed in the next (patch) release.

**Comment by hpgrahsl** [comment]
@wdutkiewicz Find the patch release here https://github.com/hpgrahsl/kryptonite-for-kafka/releases/tag/v0.4.2 Give it a try and let me know if this solves the reported issue.
